name: Lint Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or your project's Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint # Assuming you have a "lint" script in your package.json
